firstname = input("Ener your firstname")
surname = input("Enter your surname")
print("Hello there"+surname+" "+forername)
print("Oops sorry, Hello there "+firstname+surname)
print("Sorry again.... Hello there "+firstname+" "+surname)