print()
print("You will meet two people - one is the sweet shop owner")
print("who wants to steal the password so he can keep the sweets.")
print()
playername = input("What is your name? ")
print("Welcome " + playername)
print()
